10 HOME
20 PRINT "***********************************"
30 PRINT " LINEAR ACCELERATION TO DISTANCE"
40 PRINT " "
50 PRINT " PLEASE ENTER ACCELERATION (M/S2)"
60 INPUT "";AC
70 PRINT " PLEASE ENTER TIME IN SECONDS"
80 INPUT "";TM
90 PRINT " MAX SPEED IN M/S"
100 PRINT AC*TM
110 PRINT " COVERED DISTANCE IN METERS "
120 PRINT (1/2)*AC*TM*TM
130 END
